"use client"
import React, { useState } from "react";

const Calculator = () => {
    const [expression, setexpression] = useState("")

    const handleButtonClick = (value: string) => {
        setexpression((prevExpression) => prevExpression + value)
    }

    const handleCalculate = () => {
        try {
            setexpression(eval(expression))
        } catch (error) {
            setexpression('Error')
        }
    }

    const handleClear = () => {
        setexpression("")
    }

    return (
        <div className="h-screen">
            <h1 className="font-bold text-5xl text-center text-black bg-slate-300 w-fit px-5 py-2 rounded-xl mt-14 mb-5 mx-auto">CALCULATOR</h1>
            <p className="font-light text-lg text-center text-black bg-slate-300 w-fit px-5 py-2 rounded-xl mt-5 mb-14 mx-auto">Generated by Hurma Nadeem</p>

            <div className="flex-col justify-center items-center w-64 mx-auto p-6 rounded-lg bg-[#000000] shadow-lg">

                <input
                    type="text"
                    className="w-full mb-5 py-2 text-xl text-right bg-[#CDCDCB] rounded-lg"
                    value={expression}
                    readOnly
                />

                <div className="grid grid-cols-4 gap-2 text-xl">

                    {['7', '8', '9', '/'].map((value, index) => (
                        <button
                            key={index}
                            className="p-2 bg-[#333333] text-white rounded-lg hover:bg-[#413f3f]"
                            onClick={() => handleButtonClick(value)}>

                            {value}

                        </button>
                    ))}
                    {['4', '5', '6', '*'].map((value, index) => (
                        <button
                            key={index}
                            className="p-2 bg-[#333333] text-white rounded-lg hover:bg-[#413f3f]"
                            onClick={() => handleButtonClick(value)}>

                            {value}

                        </button>
                    ))}
                    {['1', '2', '3', '-'].map((value, index) => (
                        <button
                            key={index}
                            className="p-2 bg-[#333333] text-white rounded-lg hover:bg-[#413f3f]"
                            onClick={() => handleButtonClick(value)}>

                            {value}

                        </button>
                    ))}
                    {['0', '.', '=', '+'].map((value, index) => (
                        <button
                            key={index}
                            className="p-2 bg-[#333333] text-white rounded-lg hover:bg-[#413f3f]"
                            onClick={() => value === '=' ? handleCalculate() : handleButtonClick(value)}>

                            {value}

                        </button>
                    ))}
                </div>

                <button className="mt-4 w-full p-2 bg-[#ff9500] text-white rounded-lg hover:bg-[#f7a120]"
                    onClick={handleClear}>
                    Clear
                </button>

            </div>



        </div>
    )
}

export default Calculator